lqr_node:
    ros__parameters:
        # SETTINGS
        is_debug_mode: true
        is_constant_speed: true
        target_speed: 7.0
        trajectory_oversampling_factor: 100
        search_radius: 4.0 # for KD-Tree, will be squared
        s_window: 0.005 # for sliding window search
        max_distance: 5.00 # maximum distance a point can be to be considered the closest one to the odometry
        dt: 0.003 # single iteartion time
        double_check: 100 # number of iterations to double check the closest point
        use_csv: true

        # SUPPORT FILES
        trajectory_filename: "/circuits/varano_s.csv"
        odom_topic: "/Odometry"
        control_topic: "/drive_parameters"
        debug_topic: "/debug/odometry"
        debug_odom_topic: "/debug/debby"
        partial_traj_topic: "/planning/centerline_enhanced"
        global_traj_topic: "/planning/global_centerline"

        # CAR PHYSICAL PARAMETERS
        car_mass: 318.0
        front_length: 0.8462
        rear_length: 0.7238
        C_alpha_front: 1e4
        C_alpha_rear: 1e4
        steering_ratio: 1.0 # should be handled by acs node if using sim

        # PID parameters
        PID_p:  5.0
        PID_i:  1.0
        PID_d:  0.0
        max_integral: 500.0 # max value the intergral term can assume

        # CONTROL VECTORS 
        vectors_k:
          - "5.00    1.3818    0.1010    1.7959    0.0948"
          - "10.0    1.3818    0.1010    1.7959    0.0948"
          - "15.0    1.3818    0.1010    1.7959    0.0948"
          - "20.0    1.3818    0.1010    1.7959    0.0948"

          