local_planner:
    ros__parameters:
        # GENERAL PARAMETERS
        node/eventType: "autocross"  # Possible values: "acceleration" "autocross" "skidpad"
        # THESE ARE I/O TOPICS, THEY ARE MEANT TO USE EFFICIENT MESSAGE TYPES
        node/topicBorders: "planning/borders" # not used by autocross
        node/topicCenterLine: "planning/center_line_delunay"
        node/topicBordersCompleted: "planning/borders_completed" # not used by autocross
        node/topicCenterLineCompleted: "planning/center_line_completed_delunay"
        node/topicRaceStatus: "planning/race_status"
        node/topicOdometry: "Odometry"
        node/topicSlamCones: "test/slam/cones_positions"

        # ACCELERATION PARAMETERS
        acceleration/lineWidth: 0.1

        # AUTOCROSS PARAMETERS
        autocross/min_cone_confidence:            0.0     # float  [-]   minimum required confidence to take a cone into account.
        autocross/max_triangle_edge_len:          10.0    # double [m]   all triangles will have all edge lenghts below max_triangle_edge_len.
        autocross/min_triangle_angle:             0.30    # double [rad] all triangles with any angle below this, will be removed.
        autocross/max_dist_circum_midPoint:       12.0    # double [m]   only take into account the midpoints that have a triangle circumcenter closer than max_dist_circum_midPoint. 
        # Search
        autocross/max_way_horizon_size:           0       # int    [num] max horizon size of the path (max number of midpoints computer ahead of the car). 0 for infinite.
        autocross/max_search_tree_height:         10      # int    [num] max length of a path in the tree search, this is the horizon length of the program. The greater the better.
        autocross/search_radius:                  5.0     # double [m]
        autocross/max_angle_diff:                 0.60    # double [rad] maximum angle difference between points in midline. Minimum 0, maximum pi/2.
        autocross/edge_len_diff_factor:           0.7     # double [-]   if the path has a mean edge length of x, a midpoint belonging to an edge e will only be considered if x-this*x < length(e) <= x+x*this
        autocross/max_search_options:             3       # int    [num] number of maximum sons of every node in the tree during the search, 2 is stable, 3 risky
        autocross/max_next_heuristic:             2.3     # double [-]
        autocross/heur_dist_ponderation:          0.4     # float  [-]   minumum 0.0, maximum 1.0. Assume heur_angle_ponderation = 1.0-this
        autocross/allow_intersection:             false   # bool   [-]   whether or not to allow path intersection (a loop in the path)
        autocross/max_treeSearch_time:            0.05    # float  [s]   maximum time that a tree search can take, otherwise, the search will be stopped and the best midpoint until then will be chosen (and appended to the path), we can assume that the overall max time will be this*num_of_midpoints_in_path_from_car_to_end
        # Loop Closure
        autocross/shutdown_on_loop_closure:       false   # bool   [-]   whether or not it will shut itself down after a loop was closed.
        autocross/max_dist_loop_closure:          1.0     # double [m]   maximum distance between first and last midpoint to consider it a loop.
        autocross/max_angle_diff_loop_closure:    0.50    # double [rad] maximum angle difference between first and last midpoints. Expected to be same as max_angle_diff but it may come in hand having two separated.
        # Replan flag
        autocross/vital_num_midpoints:            10      # int    [num] number of midpoints that are considered "vital" from the car's position on. This is taken into account when computing the (inner) replan flag.
        # Fail safe(s)
        autocross/failsafe_max_way_horizon_size:  6       # int    [num] during a failsafe event, the size of the way horizon will be set to this value. To avoid undesirable effects.
        autocross/general_failsafe:               true    # bool   [-]   whether or not to allow the general fail safe to activate. This means, when no path is possible (shorter than a constant) by using no color, it will automatically increase all search parameters by a factor. It will switch back to normal function, once the path (calculated with normal parameters) is long enough.
        autocross/general_failsafe_safetyFactor:  1.4     # double [-]   when general failsafe is activated, the search parameters will be increased by a factor.
        # Visualization
        autocross/publish_markers:                true    # bool   [-]   whether or not to publish the markers of the midpoints and the path.
        autocross/marker_topics/triangulation:    "planning/visualization_triangulation"
        autocross/marker_topics/midpoints:        "planning/visualization_midpoints"
        autocross/marker_topics/way:              "planning/visualization_way"

        # SKIDPAD PARAMETERS
        skidpad/centerX : 15.0
        skidpad/centerY : 9.125
        skidpad/innerRadius : 7.625
        skidpad/centerRadius : 9.125
        skidpad/outerRadius : 10.625
        skidpad/firstAlignCenterError : 1.0
        skidpad/firstAlignRadiusError : 1.0
        skidpad/errorIncrement : 0.1
        skidpad/centerError : 0.5
        skidpad/radiusError : 0.5
        skidpad/radiusOffsetL : 0.0
        skidpad/radiusOffsetR : 0.0
        skidpad/circlePoints : 80
        skidpad/linePoints : 30