lqr_node:
    ros__parameters:
        # SETTINGS
        is_debug_mode: true
        is_first_lap:  false
        is_constant_speed: true
        target_speed: 5.0
        trajectory_oversampling_factor: 100
        search_radius: 4.0 # will be squared
        s_window: 4.0
        max_distance: 0.5
        # SUPPORT FILES
        trajectory_filename: "/circuits/track_s.csv"
        odom_topic: "/simulation_state"
        control_topic: "/car_controls"
        debug_topic: "/debug/odometry"
        debug_odom_topic: "/debug/debby"
        partial_traj_topic: "/planning/centerline"
        # CAR PHYSICAL PARAMETERS
        car_mass: 280.0
        front_length: 0.8162
        rear_length: 0.7238
        C_alpha_front: 1e4
        C_alpha_rear: 1e4
        steering_ratio: 3.5
        # PID parameters
        PID_p:  1.0
        PID_i:  0.0
        PID_d:  0.0
        # CONTROL VECTORS 
        vectors_k:
          - "5.00    1.3520    0.1217    1.7214    0.0970"
          - "10.0    1.3520    0.1217    1.7214    0.0970"
          - "15.0    1.3520    0.1217    1.7214    0.0970"
          - "20.0    1.3520    0.1217    1.7214    0.0970"