<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="car_chassie" params="name *origin parent">
        <link name="${name}_link">
            <visual name="">
                <origin xyz="-${length/2} 0.0 ${height_from_ground}" rpy="0.0 0.0 0.0"/> 
                
                <geometry>
                    <box size="${length} ${width} ${height}"/>   
                </geometry>
                
                <material name="Orange" />
            </visual>
        </link>

        <joint name="${name}_vehicle_joint" type="fixed">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>  
            <child link="${name}_link"/>
            <parent link="vehicle"/>
        </joint>
    </xacro:macro>

</robot>

